// Code generated by go-swagger; DO NOT EDIT.

package games

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new games API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for games API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetGames gets a list of all games in a particular season
*/
func (a *Client) GetGames(params *GetGamesParams, authInfo runtime.ClientAuthInfoWriter) (*GetGamesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetGamesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getGames",
		Method:             "GET",
		PathPattern:        "/games/{season}",
		ProducesMediaTypes: []string{"*/*"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetGamesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetGamesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
