// Code generated by go-swagger; DO NOT EDIT.

package games

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetGamesParams creates a new GetGamesParams object
// with the default values initialized.
func NewGetGamesParams() *GetGamesParams {
	var ()
	return &GetGamesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetGamesParamsWithTimeout creates a new GetGamesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetGamesParamsWithTimeout(timeout time.Duration) *GetGamesParams {
	var ()
	return &GetGamesParams{

		timeout: timeout,
	}
}

// NewGetGamesParamsWithContext creates a new GetGamesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetGamesParamsWithContext(ctx context.Context) *GetGamesParams {
	var ()
	return &GetGamesParams{

		Context: ctx,
	}
}

// NewGetGamesParamsWithHTTPClient creates a new GetGamesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetGamesParamsWithHTTPClient(client *http.Client) *GetGamesParams {
	var ()
	return &GetGamesParams{
		HTTPClient: client,
	}
}

/*GetGamesParams contains all the parameters to send to the API endpoint
for the get games operation typically these are written to a http.Request
*/
type GetGamesParams struct {

	/*Season
	  Season to retrieve

	*/
	Season int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get games params
func (o *GetGamesParams) WithTimeout(timeout time.Duration) *GetGamesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get games params
func (o *GetGamesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get games params
func (o *GetGamesParams) WithContext(ctx context.Context) *GetGamesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get games params
func (o *GetGamesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get games params
func (o *GetGamesParams) WithHTTPClient(client *http.Client) *GetGamesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get games params
func (o *GetGamesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSeason adds the season to the get games params
func (o *GetGamesParams) WithSeason(season int64) *GetGamesParams {
	o.SetSeason(season)
	return o
}

// SetSeason adds the season to the get games params
func (o *GetGamesParams) SetSeason(season int64) {
	o.Season = season
}

// WriteToRequest writes these params to a swagger request
func (o *GetGamesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param season
	if err := r.SetPathParam("season", swag.FormatInt64(o.Season)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
