// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// CoinToss coin toss
// swagger:model CoinToss
type CoinToss struct {

	// coin toss winner
	CoinTossWinner string `json:"coin_toss_winner,omitempty"`

	// A free-form string that contains information on the winner of the game-starting coin toss, and what the team elected to do.
	// The structure of this value is not normalized and as such should be used programmatically with caution.
	//
	CoinTossWinnerElection string `json:"coin_toss_winner_election,omitempty"`
}

// Validate validates this coin toss
func (m *CoinToss) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CoinToss) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CoinToss) UnmarshalBinary(b []byte) error {
	var res CoinToss
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
