/*
 * CFL API
 *
 * This is an attempt to encode the CFL API using Swagger Spec.
 *
 * API version: 1.32
 * Contact: tech@cfl.ca
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type Filter struct {
	Field string `json:"field,omitempty"`
	Operator string `json:"operator,omitempty"`
	Operand string `json:"operand,omitempty"`
}
