/*
 * CFL API
 *
 * This is an attempt to encode the CFL API using Swagger Spec.
 *
 * API version: 1.32
 * Contact: tech@cfl.ca
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type Weather struct {
	// An integer value indicating the temperature taken at the stadium / venue the game is held at. Note that this value can be zero or negative. 
	Temperature int32 `json:"temperature,omitempty"`
	Sky string `json:"sky,omitempty"`
	WindSpeed string `json:"wind_speed,omitempty"`
	WindDirection string `json:"wind_direction,omitempty"`
	FieldConditions string `json:"field_conditions,omitempty"`
}
