/*
 * CFL API
 *
 * This is an attempt to encode the CFL API using Swagger Spec.
 *
 * API version: 1.32
 * Contact: tech@cfl.ca
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type Page struct {
	Number int32 `json:"number,omitempty"`
	Size int32 `json:"size,omitempty"`
}
