/*
 * CFL API
 *
 * This is an attempt to encode the CFL API using Swagger Spec.
 *
 * API version: 1.32
 * Contact: tech@cfl.ca
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
type Sort string

// List of Sort
const (
	DATE_START Sort = "date_start"
	SEASON Sort = "season"
	WEEK Sort = "week"
	TEMPERATURE Sort = "temperature"
	ATTENDANCE Sort = "attendance"
	TEAM_1 Sort = "team_1"
	TEAM_2 Sort = "team_2"
)