/*
 * CFL API
 *
 * This is an attempt to encode the CFL API using Swagger Spec.
 *
 * API version: 1.32
 * Contact: tech@cfl.ca
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Venue struct {
	// A unique numeric value assigned to the stadium / venue the game is held within.
	VenueId int32 `json:"venue_id,omitempty"`
	// The name of the stadium / venue the game is held within.
	Name string `json:"name,omitempty"`
}
