/*
 * CFL API
 *
 * This is an attempt to encode the CFL API using Swagger Spec.
 *
 * API version: 1.32
 * Contact: tech@cfl.ca
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type CoinToss struct {
	CoinTossWinner string `json:"coin_toss_winner,omitempty"`
	// A free-form string that contains information on the winner of the game-starting coin toss, and what the team elected to do. The structure of this value is not normalized and as such should be used programmatically with caution. 
	CoinTossWinnerElection string `json:"coin_toss_winner_election,omitempty"`
}
