/*
 * CFL API
 *
 * This is an attempt to encode the CFL API using Swagger Spec.
 *
 * API version: 1.32
 * Contact: tech@cfl.ca
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type Team struct {
	TeamId int32 `json:"team_id,omitempty"`
	Location string `json:"location,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	Abbreviation string `json:"abbreviation,omitempty"`
	Score int32 `json:"score,omitempty"`
	VenueId int32 `json:"venue_id,omitempty"`
	Linescores []map[string]interface{} `json:"linescores,omitempty"`
	IsAtHome bool `json:"is_at_home,omitempty"`
	IsWinner bool `json:"is_winner,omitempty"`
}
