/*
 * CFL API
 *
 * This is an attempt to encode the CFL API using Swagger Spec.
 *
 * API version: 1.32
 * Contact: tech@cfl.ca
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type PlayByPlay struct {
	PlayId int32 `json:"play_id,omitempty"`
	PlaySequence int32 `json:"play_sequence,omitempty"`
	Quarter int32 `json:"quarter,omitempty"`
	PlayClockStart string `json:"play_clock_start,omitempty"`
	PlayClockStartInSecs int32 `json:"play_clock_start_in_secs,omitempty"`
	FieldPositionStart string `json:"field_position_start,omitempty"`
	FieldPositionEnd string `json:"field_position_end,omitempty"`
	Down int32 `json:"down,omitempty"`
	YardsToGo int32 `json:"yards_to_go,omitempty"`
	PlaySummary string `json:"play_summary,omitempty"`
}
