/*
 * CFL API
 *
 * This is an attempt to encode the CFL API using Swagger Spec.
 *
 * API version: 1.32
 * Contact: tech@cfl.ca
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

type LineScore struct {
	Quarter int32 `json:"quarter,omitempty"`
	Score int32 `json:"score,omitempty"`
}
