---
swagger: "2.0"
info:
  description: "This is an attempt to encode the CFL API using Swagger Spec."
  version: "1.32"
  title: "CFL API"
  termsOfService: "http://api.cfl.ca/docs"
  contact:
    email: "tech@cfl.ca"
  license:
    name: "CFL Public Licence"
    url: "http://api.cfl.ca/key-request/public-licence"
host: "api.cfl.ca"
basePath: "/v1"
tags:
- name: "games"
  description: "Everything about CFL games"
  externalDocs:
    description: "Find out more"
    url: "http://api.cfl.ca/docs#games"
schemes:
- "https"
- "http"
paths:
  /games/{season}:
    get:
      tags:
      - "games"
      summary: "Get a list of all games in a particular season"
      description: ""
      operationId: "getGames"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - name: "season"
        in: "path"
        description: "Season to retrieve"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Games from seaon"
          schema:
            $ref: "#/definitions/Games"
      security:
      - api_key: []

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"

definitions:

  Games:
    type: "object"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/Game"

  Game:
    type: "object"
    properties:
      game_id:
        type: "integer"
        format: "int32"
      date_start:
        type: "string"
        format: "date-time"
      game_number:
        type: "integer"
        format: "int32"
      week:
        type: "integer"
        format: "int32"
      season:
        type: "integer"
        format: "int32"
      attendance:
        type: "integer"
        format: "int32"
      event_type:
        type: "object"
        $ref: "#/definitions/EventType"
      event_status:
        type: "object"
        $ref: "#/definitions/EventStatus"
      venue:
        type: "object"
        $ref: "#/definitions/Venue"
      weather:
        type: "object"
        $ref: "#/definitions/Weather"
      coin_toss:
        type: "object"
        $ref: "#/definitions/CoinToss"
      tickets_url:
        type: "string"

  EventType:
    type: "object"
    properties:
      event_type_id:
        type: "integer"
        format: "int32"
        description: |
          An integer value indicating the type of game played. Possible values are:
          0: Preseason
          1: Regular Season
          2: Playoffs
          3: Grey Cup
        enum:
        - 0
        - 1
        - 2
        - 3
      name:
        type: "string"
      title:
        type: "string"
        description: |
          An string value indicating the formal title of the game. Possible values can include:
          Blank / No value
          Eastern Semi-Final
          Western Semi-Final
          Eastern Final
          Western Final
          XXXth Grey Cup

  EventStatus:
    type: "object"
    properties:
      event_status_id:
        type: "integer"
        format: "int32"
        description: |
          An integer value indicating the current status of the game. Possible values are:
          1: Pre-Game
          2: In-Progress
          4: Final
          9: Cancelled
        enum:
        - 1
        - 2
        - 4
        - 9
      name:
        type: "string"
      is_active:
        type: "boolean"
        description: |
          A Boolean value indicating if play is currently live in this game. If play is live at the time of the API request, the value returned is true; else it is false.
      quarter:
        type: "integer"
        format: "int32"
        description: |
          If this game is in progress, contains an integer value indicating the current quarter of play. Contains null if the game is not in play.
      minutes:
        type: "integer"
        format: "int32"
        description: |
          If this game is in progress, contains an integer value indicating the last recorded minute value of the game clock. Contains null if the game is not in play.
      seconds:
        type: "integer"
        format: "int32"
        description: |
          If this game is in progress, contains an integer value indicating the last recorded second value of the game clock. Contains null if the game is not in play.
      down:
        type: "integer"
        format: "int32"
        description: |
          If this game is in progress, contains an integer value indicating the down of the last recorded play. Contains null if the game is not in play.
      yards_to_go:
        type: "integer"
        format: "int32"
        description: |
          If this game is in progress, contains an integer value indicating the last recorded number of yards to a first down. Contains null if the game is not in play.

  Venue:
    type: "object"
    properties:
      venue_id:
        type: "integer"
        format: "int32"
        description: |
          A unique numeric value assigned to the stadium / venue the game is held within.
      name:
        type: "string"
        description: |
          The name of the stadium / venue the game is held within.

  Weather:
    type: "object"
    properties:
      temperature:
        type: "integer"
        format: "int32"
        description: |
          An integer value indicating the temperature taken at the stadium / venue the game is held at. Note that this value can be zero or negative.
      sky:
        type: "string"
      wind_speed:
        type: "string"
      wind_direction:
        type: "string"
      field_conditions:
        type: "string"

  CoinToss:
    type: "object"
    properties:
      coin_toss_winner:
        type: "string"
      coin_toss_winner_election:
        type: "string"
        description: |
          A free-form string that contains information on the winner of the game-starting coin toss, and what the team elected to do.
          The structure of this value is not normalized and as such should be used programmatically with caution.

  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about the CFL API"
  url: "http://api.cfl.ca/docs"
